# -*- mode: ruby -*-
# vi: set ft=ruby :


# -------------------------------------------
# set your project name here. bootstrap.sh will get it
# -------------------------------------------
$projectName = "cpwt_core"


# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "hashicorp/precise64"

    config.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--memory", "1024"]
     vb.name = $projectName
  end

  # Default to the project directory.
  config.vm.synced_folder "../..", "/home/project/" + $projectName

  # bootstrap.sh assumes $projectName.mysql exists in here
  config.vm.synced_folder "../../../dump", "/home/project/dump/"

  #HTTP
  config.vm.network :forwarded_port, guest: 80, host: 8080
  #HTTPS
  config.vm.network :forwarded_port, guest: 443, host: 8443
  #mySQL
  config.vm.network :forwarded_port, guest: 3306, host: 8306

  config.vm.provision :shell, :path => "bootstrap.sh", :args => $projectName
end
